#server:
#  port: 9192
#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/hotel_db
#    username: root
#    password: 22092002
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#  servlet:
#    multipart:
#      max-file-size: 5MB
#      max-request-size: 5MB
#      file-size-threshold: 2KB
#
#


